// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Siscomat.Repositories;

#nullable disable

namespace Siscomat.Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260501212848_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Siscomat.Core.Entities.Constancia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CursoId")
                        .HasColumnType("integer")
                        .HasColumnName("curso_id");

                    b.Property<string>("FolioParticipante")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("folio_participante");

                    b.Property<int>("PlantillaId")
                        .HasColumnType("integer")
                        .HasColumnName("plantilla_id");

                    b.HasKey("Id")
                        .HasName("pk_constancias");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("ix_constancias_curso_id");

                    b.HasIndex("FolioParticipante")
                        .HasDatabaseName("ix_constancias_folio_participante");

                    b.HasIndex("PlantillaId")
                        .HasDatabaseName("ix_constancias_plantilla_id");

                    b.ToTable("constancias", (string)null);
                });

            modelBuilder.Entity("Siscomat.Core.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("ParticipanteFolio")
                        .HasColumnType("text")
                        .HasColumnName("participante_folio");

                    b.HasKey("Id")
                        .HasName("pk_cursos");

                    b.HasIndex("ParticipanteFolio")
                        .HasDatabaseName("ix_cursos_participante_folio");

                    b.ToTable("cursos", (string)null);
                });

            modelBuilder.Entity("Siscomat.Core.Entities.Gestor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("apellido1");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("apellido2");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("es_admin");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_gestores");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_gestores_correo");

                    b.ToTable("gestores", (string)null);
                });

            modelBuilder.Entity("Siscomat.Core.Entities.Participante", b =>
                {
                    b.Property<string>("Folio")
                        .HasColumnType("text")
                        .HasColumnName("folio");

                    b.Property<string>("Apellido1")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("apellido1");

                    b.Property<string>("Apellido2")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("apellido2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Folio")
                        .HasName("pk_participantes");

                    b.ToTable("participantes", (string)null);
                });

            modelBuilder.Entity("Siscomat.Core.Entities.Plantilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.HasKey("Id")
                        .HasName("pk_plantillas");

                    b.ToTable("plantillas", (string)null);
                });

            modelBuilder.Entity("Siscomat.Core.Entities.Constancia", b =>
                {
                    b.HasOne("Siscomat.Core.Entities.Curso", "Curso")
                        .WithMany("Constancias")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_constancias_cursos_curso_id");

                    b.HasOne("Siscomat.Core.Entities.Participante", "Participante")
                        .WithMany("Constancias")
                        .HasForeignKey("FolioParticipante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_constancias_participantes_folio_participante");

                    b.HasOne("Siscomat.Core.Entities.Plantilla", "Plantilla")
                        .WithMany("Constancias")
                        .HasForeignKey("PlantillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_constancias_plantillas_plantilla_id");

                    b.Navigation("Curso");

                    b.Navigation("Participante");

                    b.Navigation("Plantilla");
                });

            modelBuilder.Entity("Siscomat.Core.Entities.Curso", b =>
                {
                    b.HasOne("Siscomat.Core.Entities.Participante", null)
                        .WithMany("Cursos")
                        .HasForeignKey("ParticipanteFolio")
                        .HasConstraintName("fk_cursos_participantes_participante_folio");
                });

            modelBuilder.Entity("Siscomat.Core.Entities.Curso", b =>
                {
                    b.Navigation("Constancias");
                });

            modelBuilder.Entity("Siscomat.Core.Entities.Participante", b =>
                {
                    b.Navigation("Constancias");

                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("Siscomat.Core.Entities.Plantilla", b =>
                {
                    b.Navigation("Constancias");
                });
#pragma warning restore 612, 618
        }
    }
}
